import fs from 'node:fs'
const edit = (path, transform) => fs.writeFileSync(path, transform(fs.readFileSync(path, 'utf8')))
edit('src/components/sections/Hero.jsx', s => s.replace('Desarrollo web.<br /><em>Con propósito.</em>', 'Desarrollo web.<br /><em>Y educación.</em>'))
edit('src/components/sections/Profile.jsx', s => s.replace('className="section wrap profile"', 'className="section wrap profile" aria-labelledby="profile-title"').replace('<h2>', '<h2 id="profile-title">').replace('Desarrollo soluciones digitales y comparto lo que sé a través de la', 'Desarrollo web con propósito. Creo soluciones digitales y comparto lo que sé a través de la'))
edit('src/components/projects/Resume.jsx', s => s.replace('className="text-link resume-trigger"', 'className="button secondary resume-trigger"'))
edit('src/components/sections/Services.jsx', s => s.replace('className="services"', 'className="services" aria-labelledby="services-title"').replace('<h2>', '<h2 id="services-title">'))
edit('src/components/sections/Projects.jsx', s => s.replace('className="section wrap"', 'className="section wrap" aria-labelledby="projects-title"').replace('<h2>', '<h2 id="projects-title">'))
edit('src/components/sections/Contact.jsx', s => s.replace('className="contact wrap"', 'className="contact wrap" aria-labelledby="contact-title"').replace('<h2>', '<h2 id="contact-title">'))
edit('src/components/sections/TeachingExperience.jsx', s => s.replace('              <h4>Materias y áreas</h4>', '              <details className="teaching-details">\n                <summary>Ver materias y experiencia</summary>\n              <h4>Materias y áreas</h4>').replace('            </article>', '              </details>\n            </article>'))
edit('src/data/screenshots.js', s => s.replace(").sort(([a], [b]) => a.localeCompare(b, 'es', { numeric: true }))", ").map(([path]) => [path, `${import.meta.env.BASE_URL}${path.replace('/public/', '')}`])\n  .sort(([a], [b]) => a.localeCompare(b, 'es', { numeric: true }))"))
edit('src/styles/index.css', s => s.replace('--section-space: clamp(56px, 6vw, 88px);', '--section-space: clamp(48px, 5.5vw, 80px);\n  --radius-control: 8px;\n  --radius-media: 12px;').replace('body { margin: 0; }', 'body { margin: 0; }\nimg { max-width: 100%; }\nmain, .wrap, article { min-width: 0; }').replace("h1, h2, h3 { text-wrap: balance; }", "h1, h2, h3 { text-wrap: balance; }\np { text-wrap: pretty; }\n@media (prefers-reduced-motion: no-preference) {\n  button, .button, .text-link, .nav-cta, .nav-links > a {\n    transition: background-color 160ms ease, color 160ms ease, border-color 160ms ease, transform 160ms ease;\n  }\n}"))
edit('src/styles/App.css', s => s
  .replace('font-size: clamp(42px, 4.5vw, 64px)', 'font-size: clamp(42px, 4.6vw, 64px)')
  .replace('min-height: 76px;', 'min-height: 72px;')
  .replace('grid-template-columns: 1.35fr .8fr; align-items: center; gap: 72px; padding-block: 56px 64px;', 'grid-template-columns: 1.35fr .85fr; align-items: center; gap: 64px; padding-block: 48px 56px;')
  .replace('.resume-trigger { margin-left: 8px; }', '.resume-trigger { margin-left: 0; }')
  .replace('max-width: 355px;', 'max-width: 380px;')
  .replace('aspect-ratio: 1 / 1.1;', 'aspect-ratio: 1 / 1.04;')
  .replace('grid-template-columns: .85fr 1.15fr; gap: 80px;', 'grid-template-columns: .75fr 1.25fr; gap: 64px;')
  .replace('.technology-groups { display: grid; grid-template-columns: 1.3fr .9fr 1fr; gap: 36px; }', '.technology-groups { display: grid; grid-template-columns: 1.3fr .9fr 1fr; gap: 32px; padding-block: 24px; border-top: 1px solid var(--ui-line); }')
  .replace('padding: 7px 12px; border: 1px solid var(--ui-line); border-radius: 8px; font-size: 16px;', 'padding: 4px 0; border: 0; font-size: 19px;')
  .replace('.technology-group ul { display: flex; flex-wrap: wrap; gap: 10px;', '.technology-group ul { display: flex; flex-wrap: wrap; gap: 8px 20px;')
  .replace('.service-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 0 48px; }', '.service-grid { display: grid; grid-template-columns: 1fr; gap: 0; }')
  .replace('.service-grid article { position: relative; padding-block: 28px; border-top: 1px solid var(--ui-line); }', '.service-grid article { display: grid; grid-template-columns: .8fr 1.2fr; gap: 12px 48px; position: relative; padding-block: 28px; border-top: 1px solid var(--ui-line); }')
  .replace('grid-template-columns: 1fr 1fr; gap: 12px 48px;', 'grid-template-columns: .8fr 1.2fr; gap: 12px 48px;')
  .replace('margin-top: 24px; font-size: 11px; letter-spacing: .07em;', 'margin-top: 0; font-size: 12px; letter-spacing: .03em;')
  .replace('.service-link { margin-top: 8px; }', '.service-link { margin-top: 0; justify-self: start; }')
  .replace(".process li::before { content: '0' counter(process); display: block; font-size: 13px; color: var(--ui-accent); margin-bottom: 8px; }", '.process li { border-left: 2px solid var(--ui-line); padding-left: 20px; }')
  .replace('.project-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 48px 32px;', '.project-grid { display: grid; grid-template-columns: 1.15fr 1fr; gap: 56px 40px;')
  .replace('.project-notas { grid-template-columns: 1fr 1.35fr; }', '.project-notas { grid-template-columns: 1fr 1.35fr; }\n.project-buen-clima .project-title, .project-notas .project-title { font-size: clamp(28px, 2.6vw, 36px); }\n.project-buen-clima .grades-real-preview img, .project-notas .grades-real-preview img { box-shadow: 0 12px 28px #202b370c; }')
  .replace('.project-meta { display: flex; flex-wrap: wrap; gap: 6px 16px;', '.project-meta { display: flex; flex-direction: column; align-items: flex-start; gap: 6px 16px;')
  .replace('.project-meta > span:last-child { color: var(--ui-accent); font-weight: 600; }', '.project-meta > span:last-child { color: var(--ui-accent); font-weight: 600; font-size: 13px; }')
  .replace('.contact-layout { display: grid; grid-template-columns: .9fr 1.1fr; gap: 72px;', '.contact-layout { display: grid; grid-template-columns: .9fr 1.1fr; gap: 56px;')
  .replace('.contact-form { padding: 32px;', '.contact-form { padding: 28px;')
  .replace('.service-grid article:last-child { display: block; }', '.service-grid article, .service-grid article:last-child { display: block; }\n  .service-foot { margin-top: 20px; }')
  .replace('.hero-portrait { justify-self: start; max-width: 340px; }', '.hero-portrait { justify-self: start; max-width: 100%; }')
  .replace('.portrait-frame { aspect-ratio: 1.35; }', '.portrait-frame { aspect-ratio: 1.45; max-height: 360px; }')
)
edit('src/styles/TeachingExperience.css', s => s
  .replace('.teaching-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 36px 48px; }', '.teaching-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 28px 48px; }')
  .replace('margin-bottom: 24px; }', 'margin-bottom: 16px; }')
  .replace('.teaching-method { margin-top: 48px; padding: 32px;', '.teaching-method { margin-top: 40px; padding: 28px;')
  + '\n.teaching-details summary { cursor: pointer; color: var(--ui-accent); font-size: 14px; font-weight: 600; padding-block: 12px; min-height: 46px; }\n.teaching-details summary:hover { text-decoration: underline; text-underline-offset: 4px; }\n.teaching-details[open] summary { margin-bottom: 16px; }\n.teaching-details[open] { padding-bottom: 12px; }\n.teaching-role { max-width: 46ch; }\n@media (max-width: 767px) { .teaching-card { padding-top: 20px; } }\n')
